/** Academic structure entity definitions for reusable CRUD pages. */

export const ACADEMIC_DEFINITIONS = {
  'academic-years': {
    key: 'academic-years',
    label: 'Academic Year',
    labelPlural: 'Academic Years',
    serviceKey: 'academicYears',
    scope: 'master',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'start_date', label: 'Start Date', type: 'date', required: true },
      { name: 'end_date', label: 'End Date', type: 'date', required: true },
      { name: 'is_current', label: 'Current Year', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Draft', value: 'draft' },
          { label: 'Active', value: 'active' },
          { label: 'Frozen', value: 'frozen' },
          { label: 'Closed', value: 'closed' },
          { label: 'Archived', value: 'archived' },
        ],
      },
      { name: 'financial_year_label', label: 'Financial Year', type: 'text' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'school_name', header: 'School' },
      { accessorKey: 'status', header: 'Status' },
      { accessorKey: 'start_date', header: 'Start' },
      { accessorKey: 'end_date', header: 'End' },
      { accessorKey: 'is_current', header: 'Current', cell: ({ getValue }) => (getValue() ? 'Yes' : 'No') },
    ],
  },
  terms: {
    key: 'terms',
    label: 'Term',
    labelPlural: 'Terms',
    serviceKey: 'terms',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'academic_year_id', label: 'Academic Year', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'start_date', label: 'Start Date', type: 'date', required: true },
      { name: 'end_date', label: 'End Date', type: 'date', required: true },
      { name: 'sequence', label: 'Sequence', type: 'number' },
      {
        name: 'term_type',
        label: 'Term Type',
        type: 'select',
        options: [
          { label: 'Semester', value: 'semester' },
          { label: 'Trimester', value: 'trimester' },
          { label: 'Quarter', value: 'quarter' },
          { label: 'Term', value: 'term' },
          { label: 'Custom', value: 'custom' },
        ],
      },
      { name: 'weightage', label: 'Weightage', type: 'number' },
      { name: 'is_current', label: 'Current', type: 'checkbox' },
      { name: 'is_locked', label: 'Locked', type: 'checkbox' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      { accessorKey: 'term_type', header: 'Type' },
      { accessorKey: 'academic_year_name', header: 'Academic Year' },
      { accessorKey: 'weightage', header: 'Weight' },
    ],
  },
  'class-sections': {
    key: 'class-sections',
    label: 'Active Class',
    labelPlural: 'Active Classes',
    serviceKey: 'classSections',
    scope: 'school',
    // List/activate in ClassSectionActivationPage. Create STD/Section/Map under Masters.
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'academic_year_id', label: 'Academic Year', type: 'text', required: true },
      { name: 'school_class', label: 'Class', type: 'text', required: true },
      { name: 'section', label: 'Section', type: 'text', required: true },
      { name: 'stream', label: 'Stream', type: 'text' },
      { name: 'room_number', label: 'Room', type: 'text' },
      { name: 'capacity', label: 'Capacity', type: 'number' },
      { name: 'color', label: 'Color', type: 'text' },
      {
        name: 'status',
        label: 'Status',
        type: 'select',
        options: [
          { label: 'Active', value: 'active' },
          { label: 'Inactive', value: 'inactive' },
          { label: 'Full', value: 'full' },
        ],
      },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'class_name', header: 'Class' },
      { accessorKey: 'section_name', header: 'Section' },
      { accessorKey: 'stream_name', header: 'Stream' },
      { accessorKey: 'capacity', header: 'Capacity' },
      { accessorKey: 'status', header: 'Status' },
    ],
  },
  curriculums: {
    key: 'curriculums',
    label: 'Curriculum',
    labelPlural: 'Curriculums',
    serviceKey: 'curriculums',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'academic_year_id', label: 'Academic Year', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'school_class', label: 'Class', type: 'text', required: true },
      { name: 'board', label: 'Board', type: 'text' },
      { name: 'stream', label: 'Stream', type: 'text' },
      {
        name: 'curriculum_type',
        label: 'Type',
        type: 'select',
        options: [
          { label: 'CBSE', value: 'cbse' },
          { label: 'ICSE', value: 'icse' },
          { label: 'ISC', value: 'isc' },
          { label: 'State Board', value: 'state_board' },
          { label: 'IGCSE', value: 'igcse' },
          { label: 'IB', value: 'ib' },
          { label: 'Cambridge', value: 'cambridge' },
          { label: 'Custom', value: 'custom' },
        ],
      },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'curriculum_type', header: 'Type' },
      { accessorKey: 'class_name', header: 'Class' },
      { accessorKey: 'board_name', header: 'Board' },
    ],
  },
  'curriculum-subjects': {
    key: 'curriculum-subjects',
    label: 'Curriculum Subject',
    labelPlural: 'Curriculum Subjects',
    serviceKey: 'curriculumSubjects',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'curriculum', label: 'Curriculum', type: 'text', required: true },
      { name: 'subject', label: 'Subject', type: 'text', required: true },
      { name: 'is_mandatory', label: 'Mandatory', type: 'checkbox' },
      { name: 'weekly_periods', label: 'Weekly Periods', type: 'number' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'curriculum_name', header: 'Curriculum' },
      { accessorKey: 'subject_name', header: 'Subject' },
      { accessorKey: 'is_mandatory', header: 'Mandatory', cell: ({ getValue }) => (getValue() ? 'Yes' : 'No') },
      { accessorKey: 'weekly_periods', header: 'Periods/Week' },
    ],
  },
  'elective-subjects': {
    key: 'elective-subjects',
    label: 'Elective Subject',
    labelPlural: 'Elective Subjects',
    serviceKey: 'electiveSubjects',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'curriculum', label: 'Curriculum', type: 'text', required: true },
      { name: 'subject', label: 'Subject', type: 'text', required: true },
      { name: 'subject_group', label: 'Subject Group', type: 'text' },
      { name: 'min_pick', label: 'Min Pick', type: 'number' },
      { name: 'max_pick', label: 'Max Pick', type: 'number' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'curriculum_name', header: 'Curriculum' },
      { accessorKey: 'subject_name', header: 'Subject' },
      { accessorKey: 'subject_group_name', header: 'Group' },
      { accessorKey: 'min_pick', header: 'Min' },
      { accessorKey: 'max_pick', header: 'Max' },
    ],
  },
  'class-teachers': {
    key: 'class-teachers',
    label: 'Class Teacher Mapping',
    labelPlural: 'Class Teacher Mappings',
    serviceKey: 'classTeachers',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'academic_year_id', label: 'Academic Year', type: 'text', required: true },
      { name: 'class_section', label: 'Class Section', type: 'text', required: true },
      { name: 'teacher', label: 'Teacher', type: 'text', required: true },
      { name: 'is_primary', label: 'Primary Teacher', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'class_section_label', header: 'Class Section' },
      { accessorKey: 'teacher_name', header: 'Teacher' },
      { accessorKey: 'is_primary', header: 'Primary', cell: ({ getValue }) => (getValue() ? 'Yes' : 'No') },
    ],
  },
  'calendar-events': {
    key: 'calendar-events',
    label: 'Calendar Event',
    labelPlural: 'Academic Calendar',
    serviceKey: 'calendarEvents',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'academic_year_id', label: 'Academic Year', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'event_type', label: 'Event Type', type: 'select', options: [
        { label: 'Term', value: 'term' },
        { label: 'Exam', value: 'exam' },
        { label: 'Holiday', value: 'holiday' },
        { label: 'Event', value: 'event' },
        { label: 'Meeting', value: 'meeting' },
        { label: 'Admission', value: 'admission' },
        { label: 'Other', value: 'other' },
      ]},
      { name: 'start_date', label: 'Start Date', type: 'date', required: true },
      { name: 'end_date', label: 'End Date', type: 'date' },
      { name: 'is_all_day', label: 'All Day', type: 'checkbox' },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'event_type', header: 'Type' },
      { accessorKey: 'start_date', header: 'Start' },
      { accessorKey: 'end_date', header: 'End' },
    ],
  },
  'class-timings': {
    key: 'class-timings',
    label: 'Class Timing',
    labelPlural: 'Class Timings',
    serviceKey: 'classTimings',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'academic_year_id', label: 'Academic Year', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'shift_start', label: 'Shift Start', type: 'text', required: true },
      { name: 'shift_end', label: 'Shift End', type: 'text', required: true },
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'shift_start', header: 'Start' },
      { accessorKey: 'shift_end', header: 'End' },
    ],
  },
  periods: {
    key: 'periods',
    label: 'Period',
    labelPlural: 'Periods',
    serviceKey: 'periods',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'class_timing', label: 'Class Timing', type: 'text', required: true },
      { name: 'period_number', label: 'Period #', type: 'number', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'start_time', label: 'Start Time', type: 'text', required: true },
      { name: 'end_time', label: 'End Time', type: 'text', required: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'class_timing_name', header: 'Timing' },
      { accessorKey: 'period_number', header: '#' },
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'start_time', header: 'Start' },
      { accessorKey: 'end_time', header: 'End' },
    ],
  },
  'working-days': {
    key: 'working-days',
    label: 'Working Day',
    labelPlural: 'Working Days',
    serviceKey: 'workingDays',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'academic_year_id', label: 'Academic Year', type: 'text', required: true },
      { name: 'weekday', label: 'Weekday (0=Mon)', type: 'number', required: true },
      { name: 'is_working', label: 'Working Day', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'weekday_label', header: 'Day' },
      { accessorKey: 'is_working', header: 'Working', cell: ({ getValue }) => (getValue() ? 'Yes' : 'No') },
    ],
  },
  holidays: {
    key: 'holidays',
    label: 'Holiday',
    labelPlural: 'Holiday Calendar',
    serviceKey: 'holidays',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'academic_year_id', label: 'Academic Year', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'holiday_date', label: 'Date', type: 'date', required: true },
      { name: 'holiday_type', label: 'Type', type: 'select', options: [
        { label: 'Public', value: 'public' },
        { label: 'School', value: 'school' },
        { label: 'Optional', value: 'optional' },
      ]},
      { name: 'description', label: 'Description', type: 'textarea', fullWidth: true },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'holiday_date', header: 'Date' },
      { accessorKey: 'holiday_type', header: 'Type' },
    ],
  },
  boards: {
    key: 'boards',
    label: 'Board',
    labelPlural: 'Boards',
    serviceKey: 'boards',
    scope: 'master',
    masterKey: 'boards',
  },
  classes: {
    key: 'classes',
    label: 'Class',
    labelPlural: 'Classes',
    serviceKey: 'classes',
    scope: 'master',
    masterKey: 'classes',
  },
  sections: {
    key: 'sections',
    label: 'Section',
    labelPlural: 'Sections',
    serviceKey: 'sections',
    scope: 'master',
    masterKey: 'sections',
  },
  streams: {
    key: 'streams',
    label: 'Stream',
    labelPlural: 'Streams',
    serviceKey: 'streams',
    scope: 'master',
    masterKey: 'streams',
  },
  subjects: {
    key: 'subjects',
    label: 'Subject',
    labelPlural: 'Subjects',
    serviceKey: 'subjects',
    scope: 'master',
    masterKey: 'subjects',
  },
  'subject-groups': {
    key: 'subject-groups',
    label: 'Subject Group',
    labelPlural: 'Subject Groups',
    serviceKey: 'subjectGroups',
    scope: 'master',
    masterKey: 'subject-groups',
  },
  'grading-schemes': {
    key: 'grading-schemes',
    label: 'Grading Scheme',
    labelPlural: 'Grading Schemes',
    serviceKey: 'gradingSchemes',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      {
        name: 'result_type',
        label: 'Result Type',
        type: 'select',
        options: [
          { label: 'Marks', value: 'marks' },
          { label: 'Grades', value: 'grades' },
          { label: 'CGPA', value: 'cgpa' },
          { label: 'Percentage', value: 'percentage' },
          { label: 'Credits', value: 'credits' },
          { label: 'Custom', value: 'custom' },
        ],
      },
      { name: 'passing_marks', label: 'Passing Marks', type: 'number' },
      { name: 'is_default', label: 'Default', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'result_type', header: 'Type' },
      { accessorKey: 'passing_marks', header: 'Pass Marks' },
    ],
  },
  policies: {
    key: 'policies',
    label: 'Academic Policy',
    labelPlural: 'Academic Policies',
    serviceKey: 'policies',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'academic_year_id', label: 'Academic Year', type: 'text' },
      {
        name: 'kind',
        label: 'Kind',
        type: 'select',
        options: [
          { label: 'Passing', value: 'passing' },
          { label: 'Attendance', value: 'attendance' },
          { label: 'Promotion', value: 'promotion' },
          { label: 'Detention', value: 'detention' },
          { label: 'Subject Selection', value: 'subject_selection' },
          { label: 'Elective', value: 'elective' },
        ],
      },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'is_default', label: 'Default', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'kind_display', header: 'Kind' },
      { accessorKey: 'code', header: 'Code' },
    ],
  },
  'assessment-categories': {
    key: 'assessment-categories',
    label: 'Assessment Category',
    labelPlural: 'Assessment Categories',
    serviceKey: 'assessmentCategories',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'weightage', label: 'Weightage', type: 'number' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      { accessorKey: 'weightage', header: 'Weight' },
    ],
  },
  'exam-types': {
    key: 'exam-types',
    label: 'Exam Type',
    labelPlural: 'Exam Types',
    serviceKey: 'examTypes',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'weightage', label: 'Weightage', type: 'number' },
      { name: 'max_marks', label: 'Max Marks', type: 'number' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'weightage', header: 'Weight' },
      { accessorKey: 'max_marks', header: 'Max Marks' },
    ],
  },
  rooms: {
    key: 'rooms',
    label: 'Room',
    labelPlural: 'Rooms',
    serviceKey: 'rooms',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'name', label: 'Name', type: 'text', required: true },
      { name: 'code', label: 'Code', type: 'text', required: true, readOnlyOnEdit: true },
      { name: 'room_type', label: 'Type', type: 'text' },
      { name: 'capacity', label: 'Capacity', type: 'number' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'name', header: 'Name' },
      { accessorKey: 'code', header: 'Code' },
      { accessorKey: 'room_type', header: 'Type' },
      { accessorKey: 'capacity', header: 'Capacity' },
    ],
  },
  'class-section-subjects': {
    key: 'class-section-subjects',
    label: 'Class Subject',
    labelPlural: 'Class Section Subjects',
    serviceKey: 'classSectionSubjects',
    scope: 'school',
    fields: [
      { name: 'school_id', label: 'School', type: 'text', required: true },
      { name: 'academic_year_id', label: 'Academic Year', type: 'text', required: true },
      { name: 'class_section', label: 'Class Section', type: 'text', required: true },
      { name: 'subject', label: 'Subject', type: 'text', required: true },
      { name: 'teacher', label: 'Teacher', type: 'text' },
      { name: 'weekly_periods', label: 'Weekly Periods', type: 'number' },
      { name: 'is_elective', label: 'Elective', type: 'checkbox' },
      { name: 'is_active', label: 'Active', type: 'checkbox' },
    ],
    columns: [
      { accessorKey: 'class_section_label', header: 'Class Section' },
      { accessorKey: 'subject_name', header: 'Subject' },
      { accessorKey: 'teacher_name', header: 'Teacher' },
    ],
  },
}

export const ACADEMIC_HUB_GROUPS = [
  {
    title: 'Academic Setup',
    items: [
      {
        key: 'admission-setup-view',
        label: 'Academic Years',
        path: '/academics/admission-setup',
        description: 'View years from Admissions → Setup (manage there)',
      },
      { key: 'terms', label: 'Terms / Semesters', path: '/academics/terms' },
    ],
  },
  {
    title: 'Curriculum',
    items: [
      { key: 'curriculums', label: 'Curriculum', path: '/academics/curriculums' },
      { key: 'curriculum-subjects', label: 'Curriculum Subjects', path: '/academics/curriculum-subjects' },
      { key: 'elective-subjects', label: 'Elective Subjects', path: '/academics/elective-subjects' },
    ],
  },
  {
    title: 'Calendar & Timetable Foundation',
    items: [
      { key: 'calendar-events', label: 'Academic Calendar', path: '/academics/calendar-events' },
      { key: 'working-days', label: 'Working Days', path: '/academics/working-days' },
      { key: 'holidays', label: 'Holiday Calendar', path: '/academics/holidays' },
      { key: 'class-timings', label: 'Class Timings', path: '/academics/class-timings' },
      { key: 'periods', label: 'Periods', path: '/academics/periods' },
    ],
  },
  {
    title: 'Assessment & Policies Foundation',
    items: [
      { key: 'grading-schemes', label: 'Grading Schemes', path: '/academics/grading-schemes' },
      { key: 'assessment-categories', label: 'Assessment Categories', path: '/academics/assessment-categories' },
      { key: 'exam-types', label: 'Exam Types', path: '/academics/exam-types' },
      { key: 'policies', label: 'Academic Policies', path: '/academics/policies' },
    ],
  },
]
