export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/api/auth/login/',
    REFRESH: '/api/auth/refresh/',
    LOGOUT: '/api/auth/logout/',
    PROFILE: '/api/auth/profile/',
    CHANGE_PASSWORD: '/api/auth/change-password/',
  },
  DASHBOARD: {
    SUPER_ADMIN: '/api/v1/dashboard/super-admin/',
    SUPER_ADMIN_SUMMARY: '/api/v1/dashboard/super-admin/summary/',
    SCHOOL_ADMIN: '/api/v1/dashboard/school-admin/',
    SCHOOL_ADMIN_SUMMARY: '/api/v1/dashboard/school-admin/summary/',
    STUDENT_SUMMARY: '/api/v1/dashboard/student/summary/',
    STUDENT_CALENDAR: '/api/v1/dashboard/student/calendar/',
    TEACHER_SUMMARY: '/api/v1/dashboard/teacher/summary/',
    TEACHER_CALENDAR: '/api/v1/dashboard/teacher/calendar/',
    TEACHER_CLASS_STUDENTS: '/api/v1/dashboard/teacher/class-students/',
  },
  HEALTH: '/api/v1/health/',
  REGISTER: '/api/v1/accounts/register/',
  ORGANIZATIONS: {
    LIST: '/api/v1/organizations/',
    DETAIL: (id) => `/api/v1/organizations/${id}/`,
    ACTIVATE: (id) => `/api/v1/organizations/${id}/activate/`,
    DEACTIVATE: (id) => `/api/v1/organizations/${id}/deactivate/`,
    SUSPEND: (id) => `/api/v1/organizations/${id}/suspend/`,
    UPLOAD_DOCUMENTS: (id) => `/api/v1/organizations/${id}/upload-documents/`,
    DELETE_DOCUMENT: (id, documentId) => `/api/v1/organizations/${id}/documents/${documentId}/`,
    SETTINGS: (id) => `/api/v1/organizations/${id}/settings/`,
    BRANDING: (id) => `/api/v1/organizations/${id}/branding/`,
    SUBSCRIPTION: (id) => `/api/v1/organizations/${id}/subscription/`,
    ASSIGN_SUBSCRIPTION: (id) => `/api/v1/organizations/${id}/subscription/assign/`,
    FEATURES: (id) => `/api/v1/organizations/${id}/features/`,
    DOMAINS: (id) => `/api/v1/organizations/${id}/domains/`,
    USAGE: (id) => `/api/v1/organizations/${id}/usage/`,
    BACKUPS: (id) => `/api/v1/organizations/${id}/backups/`,
    SAAS_OVERVIEW: (id) => `/api/v1/organizations/${id}/saas-overview/`,
    CLONE: (id) => `/api/v1/organizations/${id}/clone/`,
    ANALYTICS: '/api/v1/organizations/analytics/',
  },
  SUBSCRIPTION_PLANS: {
    LIST: '/api/v1/subscription-plans/',
    DETAIL: (id) => `/api/v1/subscription-plans/${id}/`,
  },
  MEMBERSHIPS: {
    LIST: '/api/v1/memberships/',
    DETAIL: (id) => `/api/v1/memberships/${id}/`,
  },
  SCHOOLS: {
    LIST: '/api/v1/schools/',
    DETAIL: (id) => `/api/v1/schools/${id}/`,
    PROFILE: (id) => `/api/v1/schools/${id}/profile/`,
    PROFILE_REGENERATE_QR: (id) => `/api/v1/schools/${id}/profile/regenerate-qr/`,
    UPLOAD_DOCUMENTS: (id) => `/api/v1/schools/${id}/upload-documents/`,
    DELETE_DOCUMENT: (id, documentId) => `/api/v1/schools/${id}/documents/${documentId}/`,
    ACTIVATE: (id) => `/api/v1/schools/${id}/activate/`,
    DEACTIVATE: (id) => `/api/v1/schools/${id}/deactivate/`,
    SUSPEND: (id) => `/api/v1/schools/${id}/suspend/`,
    BRANDING: (id) => `/api/v1/schools/${id}/branding/`,
    FEATURES: (id) => `/api/v1/schools/${id}/features/`,
    ACADEMIC_CONFIG: (id) => `/api/v1/schools/${id}/academic-config/`,
    ANALYTICS: (id) => `/api/v1/schools/${id}/analytics/`,
    SAAS_OVERVIEW: (id) => `/api/v1/schools/${id}/saas-overview/`,
    CLONE: (id) => `/api/v1/schools/${id}/clone/`,
    EXPORT: '/api/v1/schools/export/',
    IMPORT: '/api/v1/schools/import/',
    INFRASTRUCTURE: (id) => `/api/v1/schools/${id}/infrastructure/`,
    INFRASTRUCTURE_DETAIL: (id, infraId) => `/api/v1/schools/${id}/infrastructure/${infraId}/`,
    CALENDAR: (id) => `/api/v1/schools/${id}/calendar/`,
    TIMINGS: (id) => `/api/v1/schools/${id}/timings/`,
    INTEGRATIONS: (id) => `/api/v1/schools/${id}/integrations/`,
    STAFF_ASSIGNMENTS: (id) => `/api/v1/schools/${id}/staff-assignments/`,
  },
  SCHOOL_PROFILE: '/api/v1/school-profile/',
  ACADEMIC_YEARS: {
    LIST: '/api/v1/academic-years/',
    DETAIL: (id) => `/api/v1/academic-years/${id}/`,
    SETTINGS: (id) => `/api/v1/academic-years/${id}/settings/`,
    SET_CURRENT: (id) => `/api/v1/academic-years/${id}/set-current/`,
    FREEZE: (id) => `/api/v1/academic-years/${id}/freeze/`,
    UNFREEZE: (id) => `/api/v1/academic-years/${id}/unfreeze/`,
    LOCK: (id) => `/api/v1/academic-years/${id}/lock/`,
    UNLOCK: (id) => `/api/v1/academic-years/${id}/unlock/`,
    CLOSE: (id) => `/api/v1/academic-years/${id}/close/`,
    ARCHIVE: (id) => `/api/v1/academic-years/${id}/archive/`,
    CLONE: (id) => `/api/v1/academic-years/${id}/clone/`,
    GENERATE_CALENDAR: (id) => `/api/v1/academic-years/${id}/generate-calendar/`,
  },
  ACADEMICS: {
    TERMS: '/api/v1/academics/terms/',
    CLASS_SECTIONS: '/api/v1/academics/class-sections/',
    CLASS_SECTION_MAPS: '/api/v1/academics/class-section-maps/',
    CLASS_SECTIONS_APPLY_MAPS: '/api/v1/academics/class-sections/apply-maps/',
    CURRICULUMS: '/api/v1/academics/curriculums/',
    CURRICULUM_SUBJECTS: '/api/v1/academics/curriculum-subjects/',
    ELECTIVE_SUBJECTS: '/api/v1/academics/elective-subjects/',
    CLASS_TEACHERS: '/api/v1/academics/class-teachers/',
    CALENDAR_EVENTS: '/api/v1/academics/calendar-events/',
    CLASS_TIMINGS: '/api/v1/academics/class-timings/',
    PERIODS: '/api/v1/academics/periods/',
    WORKING_DAYS: '/api/v1/academics/working-days/',
    HOLIDAYS: '/api/v1/academics/holidays/',
    GRADING_SCHEMES: '/api/v1/academics/grading-schemes/',
    GRADE_BANDS: '/api/v1/academics/grade-bands/',
    ASSESSMENT_CATEGORIES: '/api/v1/academics/assessment-categories/',
    EXAM_TYPES: '/api/v1/academics/exam-types/',
    ASSESSMENT_TEMPLATES: '/api/v1/academics/assessment-templates/',
    POLICIES: '/api/v1/academics/policies/',
    ROOMS: '/api/v1/academics/rooms/',
    TEACHER_AVAILABILITY: '/api/v1/academics/teacher-availability/',
    CLASS_SECTION_SUBJECTS: '/api/v1/academics/class-section-subjects/',
    SUBJECT_TREE: '/api/v1/academics/subject-tree/',
  },
  MDM: {
    CONTRACT: '/api/v1/mdm/contract/',
    CATALOG: '/api/v1/mdm/catalog/',
    BOARDS: '/api/v1/mdm/catalog/boards/',
    SUBJECTS: '/api/v1/mdm/catalog/subjects/',
    CURRICULUMS: '/api/v1/mdm/catalog/curriculums/',
    GRADING_SCHEMES: '/api/v1/mdm/catalog/grading-schemes/',
    CALENDARS: '/api/v1/mdm/catalog/calendars/',
    ADOPT_BOARD: '/api/v1/mdm/adopt/board/',
    ADOPT_SUBJECT: '/api/v1/mdm/adopt/subject/',
    ADOPT_GRADING: '/api/v1/mdm/adopt/grading-scheme/',
    ADOPT_CALENDAR: '/api/v1/mdm/adopt/calendar/',
    ADOPT_CURRICULUM: '/api/v1/mdm/adopt/curriculum/',
    ADOPT_PACK: '/api/v1/mdm/adopt/pack/',
    RESOLVE_ORG: '/api/v1/mdm/resolve/organization/',
    RESOLVE_SCHOOL_YEAR: '/api/v1/mdm/resolve/school-year/',
    ADOPTIONS: '/api/v1/mdm/adoptions/',
  },
  USERS: {
    LIST: '/api/v1/users/',
    DETAIL: (id) => `/api/v1/users/${id}/`,
    ACTIVATE: (id) => `/api/v1/users/${id}/activate/`,
    DEACTIVATE: (id) => `/api/v1/users/${id}/deactivate/`,
    RESET_PASSWORD: (id) => `/api/v1/users/${id}/reset-password/`,
    BULK_ACTION: '/api/v1/users/bulk-action/',
    EXPORT: '/api/v1/users/export/',
  },
  SCHOOL_USERS: {
    LIST: '/api/v1/school-users/',
    DETAIL: (id) => `/api/v1/school-users/${id}/`,
    ACTIVATE: (id) => `/api/v1/school-users/${id}/activate/`,
    DEACTIVATE: (id) => `/api/v1/school-users/${id}/deactivate/`,
    RESET_PASSWORD: (id) => `/api/v1/school-users/${id}/reset-password/`,
    SEND_CREDENTIALS: (id) => `/api/v1/school-users/${id}/send-credentials/`,
    LOGIN_HISTORY: (id) => `/api/v1/school-users/${id}/login-history/`,
    DEVICES: (id) => `/api/v1/school-users/${id}/devices/`,
    STAFF_ROLES: '/api/v1/school-users/staff-roles/',
  },
  ADMISSIONS: {
    SETUP: '/api/v1/admissions/setup/',
    SETUP_DETAIL: (id) => `/api/v1/admissions/setup/${id}/`,
    SETUP_EMAIL: '/api/v1/admissions/setup/email-settings/',
    LEADS: '/api/v1/admissions/leads/',
    LEAD_DETAIL: (id) => `/api/v1/admissions/leads/${id}/`,
    LEAD_CONVERT: (id) => `/api/v1/admissions/leads/${id}/convert/`,
    LEAD_FOLLOW_UPS: (id) => `/api/v1/admissions/leads/${id}/follow-ups/`,
    APPLICATIONS: '/api/v1/admissions/applications/',
    APPLICATION_DETAIL: (id) => `/api/v1/admissions/applications/${id}/`,
    PIPELINE_STATS: '/api/v1/admissions/applications/pipeline-stats/',
    SUBMIT_APPLICATION: (id) => `/api/v1/admissions/applications/${id}/submit-application/`,
    UPLOAD_DOCUMENT: (id) => `/api/v1/admissions/applications/${id}/upload-document/`,
    VERIFY_DOCUMENTS: (id) => `/api/v1/admissions/applications/${id}/verify-documents/`,
    ENTRANCE_TEST: (id) => `/api/v1/admissions/applications/${id}/entrance-test/`,
    INTERVIEW: (id) => `/api/v1/admissions/applications/${id}/interview/`,
    SUBMIT_APPROVAL: (id) => `/api/v1/admissions/applications/${id}/submit-approval/`,
    APPROVE: (id) => `/api/v1/admissions/applications/${id}/approve/`,
    REJECT: (id) => `/api/v1/admissions/applications/${id}/reject/`,
    COLLECT_FEE: (id) => `/api/v1/admissions/applications/${id}/collect-fee/`,
    CONFIRM: (id) => `/api/v1/admissions/applications/${id}/confirm/`,
    ENROLL: (id) => `/api/v1/admissions/applications/${id}/enroll/`,
    PREPARE_CONVERSION: (id) => `/api/v1/admissions/applications/${id}/prepare-conversion/`,
    WORKFLOW: (id) => `/api/v1/admissions/applications/${id}/workflow/`,
    SEATS: (id) => `/api/v1/admissions/applications/${id}/seats/`,
    RECEIPT: (id) => `/api/v1/admissions/applications/${id}/receipt/`,
    FOLLOW_UPS: (id) => `/api/v1/admissions/applications/${id}/follow-ups/`,
    CYCLES: '/api/v1/admissions/cycles/',
    CATEGORIES: '/api/v1/admissions/categories/',
    SEAT_MATRICES: '/api/v1/admissions/seat-matrices/',
    SEAT_ALLOCATIONS: '/api/v1/admissions/seat-allocations/',
    WORKFLOW_CONFIGS: '/api/v1/admissions/workflow-configs/',
    SCHOLARSHIP_TYPES: '/api/v1/admissions/scholarship-types/',
    FEE_INTENTS: '/api/v1/admissions/fee-intents/',
    NUMBER_SEQUENCES: '/api/v1/admissions/number-sequences/',
    ANALYTICS_FUNNEL: '/api/v1/admissions/analytics/funnel/',
    BULK_ACTION: '/api/v1/admissions/bulk-action/',
    PORTAL: (token) => `/api/v1/admissions/portal/${token}/`,
  },
  STUDENTS: {
    LIST: '/api/v1/students/',
    DETAIL: (id) => `/api/v1/students/${id}/`,
    BULK_IMPORT: '/api/v1/students/bulk-import/',
    BULK_PROMOTE: '/api/v1/students/bulk-promote/',
    BULK_SHUFFLE: '/api/v1/students/bulk-shuffle/',
    EXPORT: '/api/v1/students/export/',
    DASHBOARD: '/api/v1/students/dashboard/',
    SEARCH: '/api/v1/students/search/',
    NEXT_ADMISSION_NUMBER: '/api/v1/students/next-admission-number/',
    SIS_SETTINGS: '/api/v1/students/sis-settings/',
    REGENERATE_QR: (id) => `/api/v1/students/${id}/regenerate-qr/`,
    ID_CARD: (id) => `/api/v1/students/${id}/id-card/`,
    UPDATE_STATUS: (id) => `/api/v1/students/${id}/update-status/`,
    TRANSPORT: (id) => `/api/v1/students/${id}/transport/`,
    HOSTEL: (id) => `/api/v1/students/${id}/hostel/`,
    MEDICAL: (id) => `/api/v1/students/${id}/medical/`,
    UPLOAD_DOCUMENT: (id) => `/api/v1/students/${id}/upload-document/`,
    UPLOAD_PHOTO: (id) => `/api/v1/students/${id}/upload-photo/`,
    VERIFY_DOCUMENT: (id) => `/api/v1/students/${id}/verify-document/`,
    ACHIEVEMENTS: (id) => `/api/v1/students/${id}/achievements/`,
    DISCIPLINE: (id) => `/api/v1/students/${id}/discipline/`,
    SIBLINGS: (id) => `/api/v1/students/${id}/siblings/`,
    PROMOTE: (id) => `/api/v1/students/${id}/promote/`,
    TRANSFER: (id) => `/api/v1/students/${id}/transfer/`,
    GRADUATE: (id) => `/api/v1/students/${id}/graduate/`,
    ALUMNI: (id) => `/api/v1/students/${id}/alumni/`,
    GENERATE_RFID: (id) => `/api/v1/students/${id}/generate-rfid/`,
  },
  ATTENDANCE: {
    LIST: '/api/v1/attendance/',
    DETAIL: (id) => `/api/v1/attendance/${id}/`,
    DASHBOARD: '/api/v1/attendance/dashboard/',
    SEARCH: '/api/v1/attendance/search/',
    SETTINGS: '/api/v1/attendance/settings/',
    CALENDAR_DAY: '/api/v1/attendance/calendar-day/',
    MARK: '/api/v1/attendance/mark/',
    BULK_MARK: '/api/v1/attendance/bulk-mark/',
    CORRECT: (id) => `/api/v1/attendance/${id}/correct/`,
    APPROVE: (id) => `/api/v1/attendance/${id}/approve/`,
    EMPLOYEE_PUNCH: '/api/v1/attendance/employee-punch/',
    REPORT_DAILY: '/api/v1/attendance/reports/daily/',
    REPORT_PERCENTAGE: '/api/v1/attendance/reports/percentage/',
    DEFAULTERS: '/api/v1/attendance/analytics/defaulters/',
    POLICIES: '/api/v1/attendance/policies/',
    IMPORT: '/api/v1/attendance/import/',
    EXPORT: '/api/v1/attendance/export/',
    BIOMETRIC_DEVICES: '/api/v1/attendance/biometric/devices/',
    BIOMETRIC_INGEST: '/api/v1/attendance/biometric/ingest/',
    LEAVE_LINK: '/api/v1/attendance/leave-link/',
    SESSIONS: '/api/v1/attendance/sessions/',
  },
  TIMETABLE: {
    LIST: '/api/v1/timetable/',
    DETAIL: (id) => `/api/v1/timetable/${id}/`,
    DASHBOARD: '/api/v1/timetable/dashboard/',
    SEARCH: '/api/v1/timetable/search/',
    SETTINGS: '/api/v1/timetable/settings/',
    VERSIONS: (id) => `/api/v1/timetable/${id}/versions/`,
    PUBLISH: (versionId) => `/api/v1/timetable/versions/${versionId}/publish/`,
    CLONE: (versionId) => `/api/v1/timetable/versions/${versionId}/clone/`,
    ROLLBACK: (versionId) => `/api/v1/timetable/versions/${versionId}/rollback/`,
    SLOTS: (versionId) => `/api/v1/timetable/versions/${versionId}/slots/`,
    SLOTS_BULK: (versionId) => `/api/v1/timetable/versions/${versionId}/slots/bulk/`,
    TEACHER_SCHEDULE: '/api/v1/timetable/teacher-schedule/',
    STUDENT_SCHEDULE: '/api/v1/timetable/student-schedule/',
    ROOM_SCHEDULE: '/api/v1/timetable/room-schedule/',
    CONFLICTS: (versionId) => `/api/v1/timetable/versions/${versionId}/conflicts/`,
    RESOLVE_CONFLICT: (id) => `/api/v1/timetable/conflicts/${id}/resolve/`,
    SUBSTITUTIONS: '/api/v1/timetable/substitutions/',
    APPROVE_SUBSTITUTION: (id) => `/api/v1/timetable/substitutions/${id}/approve/`,
    SUGGEST_SUBSTITUTES: '/api/v1/timetable/suggest-substitutes/',
    RESOURCES: '/api/v1/timetable/resources/',
    RESOURCE_BOOKINGS: '/api/v1/timetable/resource-bookings/',
    FACILITY_ROOMS: '/api/v1/timetable/facility-rooms/',
    EVENTS: '/api/v1/timetable/events/',
    MEETINGS: '/api/v1/timetable/meetings/',
    ROOM_UTILIZATION: (versionId) => `/api/v1/timetable/versions/${versionId}/room-utilization/`,
    EXPORT: (versionId) => `/api/v1/timetable/versions/${versionId}/export/`,
    IMPORT: (versionId) => `/api/v1/timetable/versions/${versionId}/import/`,
    AI_JOBS: (versionId) => `/api/v1/timetable/versions/${versionId}/ai-jobs/`,
    SLOT_DETAIL: (versionId, slotId) => `/api/v1/timetable/versions/${versionId}/slots/${slotId}/`,
    VALIDATE: '/api/v1/timetable/validate/',
    AI_PARSE: '/api/v1/timetable/ai/parse/',
    AI_GENERATE: '/api/v1/timetable/ai/generate/',
    AI_REGENERATE: '/api/v1/timetable/ai/regenerate/',
    AI_MODIFY: '/api/v1/timetable/ai/modify/',
    AI_APPROVE: '/api/v1/timetable/ai/approve/',
    TEMPLATES: '/api/v1/timetable/templates/',
  },
  FEES: {
    DASHBOARD: '/api/v1/fees/dashboard/',
    SETTINGS: '/api/v1/fees/settings/',
    SEARCH: '/api/v1/fees/search/',
    CATEGORIES: '/api/v1/fees/categories/',
    CATEGORY_DETAIL: (id) => `/api/v1/fees/categories/${id}/`,
    CATEGORIES_BULK_UPLOAD: '/api/v1/fees/categories/bulk-upload/',
    FORMATS: '/api/v1/fees/formats/',
    FORMAT_DETAIL: (id) => `/api/v1/fees/formats/${id}/`,
    FORMATS_BULK_UPLOAD: '/api/v1/fees/formats/bulk-upload/',
    COMPONENTS: '/api/v1/fees/components/',
    COMPONENT_DETAIL: (id) => `/api/v1/fees/components/${id}/`,
    COMPONENTS_BULK_UPLOAD: '/api/v1/fees/components/bulk-upload/',
    HEADS: '/api/v1/fees/heads/',
    HEAD_DETAIL: (id) => `/api/v1/fees/heads/${id}/`,
    HEADS_BULK_UPLOAD: '/api/v1/fees/heads/bulk-upload/',
    LEDGER_CODES: '/api/v1/fees/ledger-codes/',
    LEDGER_CODE_DETAIL: (id) => `/api/v1/fees/ledger-codes/${id}/`,
    LEDGER_CODES_BULK_UPLOAD: '/api/v1/fees/ledger-codes/bulk-upload/',
    TEMPLATES: '/api/v1/fees/templates/',
    ASSIGNMENTS: '/api/v1/fees/assignments/',
    STUDENT_PROFILE: '/api/v1/fees/student-profile/',
    STUDENT_LEDGER: '/api/v1/fees/student-ledger/',
    INVOICES: '/api/v1/fees/invoices/',
    INVOICE_DETAIL: (id) => `/api/v1/fees/invoices/${id}/`,
    GENERATE_INVOICE: '/api/v1/fees/invoices/generate/',
    PAYMENTS: '/api/v1/fees/payments/',
    RECORD_PAYMENT: '/api/v1/fees/payments/record/',
    COLLECT_ITEMS: '/api/v1/fees/payments/collect-items/',
    STUDENT_FEE_ITEMS: '/api/v1/fees/student-fee-items/',
    CLASS_COLLECT_ROSTER: '/api/v1/fees/collect/class-roster/',
    RECEIPTS: '/api/v1/fees/receipts/',
    RECEIPT_DETAIL: (id) => `/api/v1/fees/receipts/${id}/`,
    RECEIPT_PDF: (id) => `/api/v1/fees/receipts/${id}/pdf/`,
    STRUCTURE_INVOICES: '/api/v1/fees/structure-invoices/',
    GENERATE_STRUCTURE_INVOICE: '/api/v1/fees/structure-invoices/generate/',
    STRUCTURE_INVOICE_DETAIL: (id) => `/api/v1/fees/structure-invoices/${id}/`,
    STRUCTURE_INVOICE_PDF: (id) => `/api/v1/fees/structure-invoices/${id}/pdf/`,
    GATEWAY_INTENT: '/api/v1/fees/gateway/intent/',
    CONCESSION_RULES: '/api/v1/fees/concession-rules/',
    CONCESSION_RULE_DETAIL: (id) => `/api/v1/fees/concession-rules/${id}/`,
    APPLY_CONCESSION: '/api/v1/fees/concessions/apply/',
    APPLIED_CONCESSIONS: '/api/v1/fees/concessions/applied/',
    REFRESH_CONCESSION_QUEUE: '/api/v1/fees/concessions/refresh-queue/',
    APPROVE_CONCESSION: (id) => `/api/v1/fees/concessions/${id}/approve/`,
    SCHOLARSHIP_PROGRAMS: '/api/v1/fees/scholarships/programs/',
    SCHOLARSHIP_AWARDS: '/api/v1/fees/scholarships/awards/',
    APPROVE_SCHOLARSHIP: (id) => `/api/v1/fees/scholarships/awards/${id}/approve/`,
    REFUNDS: '/api/v1/fees/refunds/',
    APPROVE_REFUND: (id) => `/api/v1/fees/refunds/${id}/approve/`,
    INTEGRATION_CHARGE: '/api/v1/fees/integrations/charge/',
    DEFAULTERS: '/api/v1/fees/analytics/defaulters/',
    CLASS_WISE_PAID: '/api/v1/fees/analytics/class-wise-paid/',
    STAFF_CHILDREN_REPORT: '/api/v1/fees/analytics/staff-children/',
    PAYMENT_METHODS: '/api/v1/fees/analytics/payment-methods/',
    EXPORT_COLLECTIONS: '/api/v1/fees/export/collections/',
    IMPORT_PAYMENTS: '/api/v1/fees/import/payments/',
    LATE_FEE_RULES: '/api/v1/fees/late-fee-rules/',
    RUN_LATE_FEES: '/api/v1/fees/late-fees/run/',
    SUB_CATEGORIES: '/api/v1/fees/sub-categories/',
    SUB_CATEGORY_DETAIL: (id) => `/api/v1/fees/sub-categories/${id}/`,
    DISCOUNT_RULES: '/api/v1/fees/discount-rules/',
    DISCOUNT_RULE_DETAIL: (id) => `/api/v1/fees/discount-rules/${id}/`,
    APPLIED_DISCOUNTS: '/api/v1/fees/discounts/applied/',
    APPLY_DISCOUNT: '/api/v1/fees/discounts/apply/',
    APPROVE_DISCOUNT: (id) => `/api/v1/fees/discounts/${id}/approve/`,
    PAYMENT_PLANS: '/api/v1/fees/payment-plans/',
    PAYMENT_PLAN_DETAIL: (id) => `/api/v1/fees/payment-plans/${id}/`,
    WALLETS: '/api/v1/fees/wallets/',
    WALLET_CREDIT: '/api/v1/fees/wallets/credit/',
    STUDENT_OVERRIDES: '/api/v1/fees/student-overrides/',
    OPENING_BALANCES: '/api/v1/fees/opening-balances/',
    COLLECTION_COUNTERS: '/api/v1/fees/collection-counters/',
    COLLECTION_COUNTER_DETAIL: (id) => `/api/v1/fees/collection-counters/${id}/`,
    DAILY_CLOSINGS: '/api/v1/fees/daily-closings/',
    TRANSPORT_STRUCTURES: '/api/v1/fees/transport-structures/',
    HOSTEL_STRUCTURES: '/api/v1/fees/hostel-structures/',
    TEMPLATE_BUILD: '/api/v1/fees/templates/build/',
    TEMPLATE_DETAIL: (id) => `/api/v1/fees/templates/${id}/`,
    DAILY_COLLECTION_REPORT: '/api/v1/fees/analytics/daily-collection/',
    OUTSTANDING_REPORT: '/api/v1/fees/analytics/outstanding/',
    COLLECTION_SUMMARY: '/api/v1/fees/analytics/collection-summary/',
    GATEWAY_WEBHOOK: '/api/v1/fees/gateway/webhook/',
  },
  ASSESSMENTS: {
    DASHBOARD: '/api/v1/assessments/dashboard/',
    SETTINGS: '/api/v1/assessments/settings/',
    SEARCH: '/api/v1/assessments/search/',
    EXAM_GROUPS: '/api/v1/assessments/exam-groups/',
    EXAMS: '/api/v1/assessments/exams/',
    EXAM_DETAIL: (id) => `/api/v1/assessments/exams/${id}/`,
    EXAM_PUBLISH: (id) => `/api/v1/assessments/exams/${id}/publish/`,
    EXAM_OPEN_MARKS: (id) => `/api/v1/assessments/exams/${id}/open-marks/`,
    EXAM_COMPONENTS: (id) => `/api/v1/assessments/exams/${id}/components/`,
    EXAM_SUBJECT_CONFIGS: (id) => `/api/v1/assessments/exams/${id}/subject-configs/`,
    EXAM_PASSING_RULES: (id) => `/api/v1/assessments/exams/${id}/passing-rules/`,
    EXAM_SCHEDULE: (id) => `/api/v1/assessments/exams/${id}/schedule/`,
    EXAM_DETECT_CONFLICTS: (id) => `/api/v1/assessments/exams/${id}/detect-conflicts/`,
    EXAM_CONFLICTS: (id) => `/api/v1/assessments/exams/${id}/conflicts/`,
    EXAM_PROCESS: (id) => `/api/v1/assessments/exams/${id}/process/`,
    EXAM_PUBLISH_RESULTS: (id) => `/api/v1/assessments/exams/${id}/publish-results/`,
    EXAM_RESULTS: (id) => `/api/v1/assessments/exams/${id}/results/`,
    MARKS: '/api/v1/assessments/marks/',
    MARKS_ENTER: '/api/v1/assessments/marks/enter/',
    MARKS_SUBMIT: (id) => `/api/v1/assessments/marks/${id}/submit/`,
    MARKS_APPROVE: (id) => `/api/v1/assessments/marks/${id}/approve/`,
    MARKS_MODERATE: (id) => `/api/v1/assessments/marks/${id}/moderate/`,
    PUBLISHED_SNAPSHOTS: '/api/v1/assessments/published-snapshots/',
    REMARKS: '/api/v1/assessments/remarks/',
    PASS_PERCENTAGE: '/api/v1/assessments/analytics/pass-percentage/',
    SUBJECT_ANALYSIS: '/api/v1/assessments/analytics/subject-analysis/',
    FAILURE_ANALYSIS: '/api/v1/assessments/reports/failure-analysis/',
    EXPORT_MARKS: '/api/v1/assessments/export/marks/',
    IMPORT_MARKS: '/api/v1/assessments/import/marks/',
    BLUEPRINTS: '/api/v1/assessments/blueprints/',
    AI_JOBS: '/api/v1/assessments/ai-jobs/',
  },
  DOCUMENTS: {
    DASHBOARD: '/api/v1/documents/dashboard/',
    SETTINGS: '/api/v1/documents/settings/',
    SEARCH: '/api/v1/documents/search/',
    TEMPLATES: '/api/v1/documents/templates/',
    TEMPLATE_DETAIL: (id) => `/api/v1/documents/templates/${id}/`,
    TEMPLATE_PUBLISH: (id) => `/api/v1/documents/templates/${id}/publish/`,
    TEMPLATE_ROLLBACK: (id) => `/api/v1/documents/templates/${id}/rollback/`,
    TEMPLATE_EXPORT: (id) => `/api/v1/documents/templates/${id}/export/`,
    TEMPLATE_IMPORT: '/api/v1/documents/templates/import/',
    GENERATE_REPORT_CARD: '/api/v1/documents/report-cards/generate/',
    BULK_REPORT_CARDS: '/api/v1/documents/report-cards/bulk/',
    CERTIFICATES: '/api/v1/documents/certificates/',
    GENERATE_TRANSCRIPT: '/api/v1/documents/transcripts/generate/',
    DOCUMENT_DETAIL: (id) => `/api/v1/documents/generated/${id}/`,
    PUBLISH_DOCUMENT: (id) => `/api/v1/documents/generated/${id}/publish/`,
    DOWNLOAD_PDF: (id) => `/api/v1/documents/generated/${id}/pdf/`,
    BULK_ZIP: '/api/v1/documents/export/bulk-zip/',
    VERIFY: (code) => `/api/v1/documents/verify/${code}/`,
    PREVIEW: '/api/v1/documents/preview/',
  },
  LIBRARY: {
    DASHBOARD: '/api/v1/library/dashboard/',
    BOOKS: '/api/v1/library/books/',
    BOOKS_BULK_IMPORT: '/api/v1/library/books/bulk-import/',
    BOOK_DETAIL: (id) => `/api/v1/library/books/${id}/`,
    ISSUES: '/api/v1/library/issues/',
    ISSUE_DETAIL: (id) => `/api/v1/library/issues/${id}/`,
    ISSUE_BOOK: '/api/v1/library/issues/issue/',
    LOOKUP_BORROWER: '/api/v1/library/issues/lookup/',
    ISSUES_REPORT: '/api/v1/library/issues/reports/issued-returned/',
    RETURN_BOOK: (id) => `/api/v1/library/issues/${id}/return/`,
    MEMBERS: '/api/v1/library/members/',
    MEMBER_DETAIL: (id) => `/api/v1/library/members/${id}/`,
  },
  TRANSPORT: {
    DASHBOARD: '/api/v1/transport/dashboard/',
    ROUTES: '/api/v1/transport/routes/',
    ROUTE_DETAIL: (id) => `/api/v1/transport/routes/${id}/`,
    VEHICLES: '/api/v1/transport/vehicles/',
    VEHICLE_DETAIL: (id) => `/api/v1/transport/vehicles/${id}/`,
    STOPS: '/api/v1/transport/stops/',
    STOP_DETAIL: (id) => `/api/v1/transport/stops/${id}/`,
    ASSIGNMENTS: '/api/v1/transport/assignments/',
    ASSIGNMENT_DETAIL: (id) => `/api/v1/transport/assignments/${id}/`,
  },
  LMS: {
    DASHBOARD: '/api/v1/lms/dashboard/',
    STUDENT_DASHBOARD: '/api/v1/lms/dashboard/student/',
    TEACHER_DASHBOARD: '/api/v1/lms/dashboard/teacher/',
    PARENT_DASHBOARD: '/api/v1/lms/dashboard/parent/',
    SETTINGS: '/api/v1/lms/settings/',
    SEARCH: '/api/v1/lms/search/',
    COURSES: '/api/v1/lms/courses/',
    COURSE_DETAIL: (id) => `/api/v1/lms/courses/${id}/`,
    COURSE_PUBLISH: (id) => `/api/v1/lms/courses/${id}/publish/`,
    COURSE_ENROLL: (id) => `/api/v1/lms/courses/${id}/enroll/`,
    COURSE_NODES: (id) => `/api/v1/lms/courses/${id}/nodes/`,
    NODE_PUBLISH: (id) => `/api/v1/lms/nodes/${id}/publish/`,
    NODE_PROGRESS: (id) => `/api/v1/lms/nodes/${id}/progress/`,
    LESSON_PLANS: '/api/v1/lms/lesson-plans/',
    LESSON_PLAN_SUBMIT: (id) => `/api/v1/lms/lesson-plans/${id}/submit/`,
    LESSON_PLAN_APPROVE: (id) => `/api/v1/lms/lesson-plans/${id}/approve/`,
    LESSON_PLAN_PUBLISH: (id) => `/api/v1/lms/lesson-plans/${id}/publish/`,
    ASSIGNMENTS: '/api/v1/lms/assignments/',
    HOMEWORK: '/api/v1/lms/homework/',
    ASSIGNMENT_ASSIGN: (id) => `/api/v1/lms/assignments/${id}/assign/`,
    SUBMISSION_SUBMIT: (id) => `/api/v1/lms/submissions/${id}/submit/`,
    SUBMISSION_REVIEW: (id) => `/api/v1/lms/submissions/${id}/review/`,
    SUBMISSION_RETURN: (id) => `/api/v1/lms/submissions/${id}/return/`,
    QUIZZES: '/api/v1/lms/quizzes/',
    QUIZ_QUESTIONS: (id) => `/api/v1/lms/quizzes/${id}/questions/`,
    QUIZ_ATTEMPT: (id) => `/api/v1/lms/quizzes/${id}/attempt/`,
    CONTENT: '/api/v1/lms/content/',
    LIVE_CLASSES: '/api/v1/lms/live-classes/',
    FORUMS: '/api/v1/lms/forums/',
    FORUM_POSTS: (id) => `/api/v1/lms/forums/${id}/posts/`,
    FEED: '/api/v1/lms/feed/',
    AI_JOBS: '/api/v1/lms/ai-jobs/',
  },
  TEACHERS: {
    LIST: '/api/v1/teachers/',
    ME: '/api/v1/teachers/me/',
    DETAIL: (id) => `/api/v1/teachers/${id}/`,
    EXPORT: '/api/v1/teachers/export/',
    DASHBOARD: '/api/v1/teachers/dashboard/',
    SEARCH: '/api/v1/teachers/search/',
    TEACHER_SETTINGS: '/api/v1/teachers/teacher-settings/',
    SEND_CREDENTIALS: (id) => `/api/v1/teachers/${id}/send-credentials/`,
    UPLOAD_PHOTO: (id) => `/api/v1/teachers/${id}/upload-photo/`,
    QUALIFICATIONS: (id) => `/api/v1/teachers/${id}/qualifications/`,
    EXPERIENCE: (id) => `/api/v1/teachers/${id}/experience/`,
    EXPERIENCE_UPDATE: (teacherId, experienceId) =>
      `/api/v1/teachers/${teacherId}/experience/${experienceId}/update/`,
    EXPERIENCE_DELETE: (teacherId, experienceId) =>
      `/api/v1/teachers/${teacherId}/experience/${experienceId}/delete/`,
    ASSIGN_SUBJECT: (id) => `/api/v1/teachers/${id}/assign-subject/`,
    ACADEMIC_ASSIGNMENTS: (id) => `/api/v1/teachers/${id}/academic-assignments/`,
    WORKLOAD: (id) => `/api/v1/teachers/${id}/workload/`,
    AVAILABILITY: (id) => `/api/v1/teachers/${id}/availability/`,
    PROFESSIONAL_CERTS: (id) => `/api/v1/teachers/${id}/professional-certifications/`,
    PERFORMANCE_FOUNDATION: (id) => `/api/v1/teachers/${id}/performance-foundation/`,
    DEACTIVATE: (id) => `/api/v1/teachers/${id}/deactivate/`,
    CLASS_TEACHER: (id) => `/api/v1/teachers/${id}/class-teacher/`,
    ATTENDANCE: (id) => `/api/v1/teachers/${id}/attendance/`,
    LEAVE: (id) => `/api/v1/teachers/${id}/leave/`,
    APPROVE_LEAVE: (id, leaveId) => `/api/v1/teachers/${id}/leave/${leaveId}/approve/`,
    PAYROLL: (id) => `/api/v1/teachers/${id}/payroll/`,
    UPLOAD_DOCUMENT: (id) => `/api/v1/teachers/${id}/upload-document/`,
    CERTIFICATES: (id) => `/api/v1/teachers/${id}/certificates/`,
    TIMETABLE: (id) => `/api/v1/teachers/${id}/timetable/`,
    LESSON_PLANS: (id) => `/api/v1/teachers/${id}/lesson-plans/`,
    HOMEWORK: (id) => `/api/v1/teachers/${id}/homework/`,
    ONLINE_CLASSES: (id) => `/api/v1/teachers/${id}/online-classes/`,
    PERFORMANCE_REVIEWS: (id) => `/api/v1/teachers/${id}/performance-reviews/`,
  },
  STAFF: {
    LIST: '/api/v1/staff/',
    DETAIL: (id) => `/api/v1/staff/${id}/`,
    EXPORT: '/api/v1/staff/export/',
    DASHBOARD: '/api/v1/staff/dashboard/',
    SEARCH: '/api/v1/staff/search/',
    ORG_CHART: '/api/v1/staff/org-chart/',
    HR_SETTINGS: '/api/v1/staff/hr-settings/',
    SEND_CREDENTIALS: (id) => `/api/v1/staff/${id}/send-credentials/`,
    RESET_PASSWORD: (id) => `/api/v1/staff/${id}/reset-password/`,
    EMERGENCY_CONTACT: (id) => `/api/v1/staff/${id}/emergency-contact/`,
    EXPERIENCE: (id) => `/api/v1/staff/${id}/experience/`,
    SKILLS: (id) => `/api/v1/staff/${id}/skills/`,
    SHIFT: (id) => `/api/v1/staff/${id}/shift/`,
    ATTENDANCE: (id) => `/api/v1/staff/${id}/attendance/`,
    LEAVE: (id) => `/api/v1/staff/${id}/leave/`,
    APPROVE_LEAVE: (id, leaveId) => `/api/v1/staff/${id}/leave/${leaveId}/approve/`,
    PAYROLL: (id) => `/api/v1/staff/${id}/payroll/`,
    UPLOAD_DOCUMENT: (id) => `/api/v1/staff/${id}/upload-document/`,
    AUDIT_LOGS: (id) => `/api/v1/staff/${id}/audit-logs/`,
    ONBOARDING_START: (id) => `/api/v1/staff/${id}/onboarding/start/`,
    ONBOARDING_STEP: (id) => `/api/v1/staff/${id}/onboarding/complete-step/`,
    TRANSFER: (id) => `/api/v1/staff/${id}/transfer/`,
    PROMOTE: (id) => `/api/v1/staff/${id}/promote/`,
    EXIT: (id) => `/api/v1/staff/${id}/exit/`,
    ASSETS: (id) => `/api/v1/staff/${id}/assets/`,
    CONFIRM: (id) => `/api/v1/staff/${id}/confirm/`,
    TRANSITION_STATUS: (id) => `/api/v1/staff/${id}/transition-status/`,
  },
  PARENTS: {
    LIST: '/api/v1/parents/',
    DETAIL: (id) => `/api/v1/parents/${id}/`,
    EXPORT: '/api/v1/parents/export/',
    DASHBOARD: '/api/v1/parents/dashboard/',
    SEARCH: '/api/v1/parents/search/',
    GUARDIAN_SETTINGS: '/api/v1/parents/guardian-settings/',
    PORTAL: (id) => `/api/v1/parents/${id}/portal/`,
    INVITE_PORTAL: (id) => `/api/v1/parents/${id}/invite-portal/`,
    SEND_CREDENTIALS: (id) => `/api/v1/parents/${id}/send-credentials/`,
    RESET_PASSWORD: (id) => `/api/v1/parents/${id}/reset-password/`,
    LINK_STUDENT: (id) => `/api/v1/parents/${id}/link-student/`,
    UNLINK_STUDENT: (id) => `/api/v1/parents/${id}/unlink-student/`,
    COMMUNICATION: (id) => `/api/v1/parents/${id}/communication/`,
    EMERGENCY_CONTACT: (id) => `/api/v1/parents/${id}/emergency-contact/`,
    GUARDIAN: (id) => `/api/v1/parents/${id}/guardian/`,
    MOBILE_APP_ACCESS: (id) => `/api/v1/parents/${id}/mobile-app-access/`,
    UPLOAD_PHOTO: (id) => `/api/v1/parents/${id}/upload-photo/`,
  },
  HOUSEHOLDS: {
    LIST: '/api/v1/households/',
    DETAIL: (id) => `/api/v1/households/${id}/`,
    ADD_MEMBER: (id) => `/api/v1/households/${id}/add-member/`,
    EMERGENCY_CONTACTS: (id) => `/api/v1/households/${id}/emergency-contacts/`,
  },
  PICKUPS: {
    LIST: '/api/v1/pickups/',
    VERIFY: '/api/v1/pickups/verify/',
    HISTORY: '/api/v1/pickups/history/',
  },
  COMMUNICATIONS: {
    TEMPLATES: '/api/v1/communications/templates/',
    TEMPLATE_DETAIL: (id) => `/api/v1/communications/templates/${id}/`,
    MESSAGES: '/api/v1/communications/messages/',
    MESSAGE_DETAIL: (id) => `/api/v1/communications/messages/${id}/`,
    PREVIEW_AUDIENCE: '/api/v1/communications/messages/preview-audience/',
    SEND: (id) => `/api/v1/communications/messages/${id}/send/`,
    SCHEDULE: (id) => `/api/v1/communications/messages/${id}/schedule/`,
    CANCEL: (id) => `/api/v1/communications/messages/${id}/cancel/`,
    DELIVERY_REPORT: (id) => `/api/v1/communications/messages/${id}/delivery-report/`,
    READ_RECEIPTS: (id) => `/api/v1/communications/messages/${id}/read-receipts/`,
    PROCESS_SCHEDULED: '/api/v1/communications/messages/process-scheduled/',
    DELIVERIES: '/api/v1/communications/deliveries/',
    DELIVERY_DETAIL: (id) => `/api/v1/communications/deliveries/${id}/`,
    MARK_READ: (id) => `/api/v1/communications/deliveries/${id}/mark-read/`,
  },
  ROLES: {
    LIST: '/api/v1/roles/',
    DETAIL: (id) => `/api/v1/roles/${id}/`,
    PERMISSIONS: (id) => `/api/v1/roles/${id}/permissions/`,
    ASSIGN_PERMISSIONS: (id) => `/api/v1/roles/${id}/permissions/assign/`,
    REMOVE_PERMISSIONS: (id) => `/api/v1/roles/${id}/permissions/remove/`,
    SYNC_PERMISSIONS: (id) => `/api/v1/roles/${id}/permissions/sync/`,
    MENUS: (id) => `/api/v1/roles/${id}/menus/`,
    ASSIGN_MENUS: (id) => `/api/v1/roles/${id}/menus/assign/`,
    REMOVE_MENUS: (id) => `/api/v1/roles/${id}/menus/remove/`,
    SYNC_MENUS: (id) => `/api/v1/roles/${id}/menus/sync/`,
  },
  PERMISSIONS: {
    LIST: '/api/v1/permissions/',
    DETAIL: (id) => `/api/v1/permissions/${id}/`,
    MATRIX: '/api/v1/permissions/matrix/',
  },
  USER_ROLES: {
    LIST: '/api/v1/user-roles/',
    DETAIL: (id) => `/api/v1/user-roles/${id}/`,
  },
  MODULES: {
    LIST: '/api/v1/modules/',
    DETAIL: (id) => `/api/v1/modules/${id}/`,
    REORDER: '/api/v1/modules/reorder/',
  },
  MENUS: {
    LIST: '/api/v1/menus/',
    DETAIL: (id) => `/api/v1/menus/${id}/`,
    MY_MENUS: '/api/v1/menus/my-menus/',
    TREE: '/api/v1/menus/tree/',
    MASTER_TREE: '/api/v1/menus/master-tree/',
    ALLOCATION_CATEGORIES: '/api/v1/menus/allocation-categories/',
    SCHOOL_ALLOCATION_TREE: '/api/v1/menus/school-allocation/tree/',
    SCHOOL_ALLOCATION_SYNC: '/api/v1/menus/school-allocation/sync/',
    USER_ALLOCATION_TREE: '/api/v1/menus/user-allocation/tree/',
    USER_ALLOCATION_SYNC: '/api/v1/menus/user-allocation/sync/',
    SCHOOL_ADMIN_TREE: '/api/v1/menus/school-admin-tree/',
    SCHOOL_MAPPING: '/api/v1/menus/school-mapping/',
    SCHOOL_MODULE: '/api/v1/menus/school-module/',
    PORTAL_ROLES: '/api/v1/menus/portal-roles/',
    SCHOOL_ROLE_TREE: '/api/v1/menus/school-role-tree/',
    SCHOOL_ROLE_MAPPING: '/api/v1/menus/school-role-mapping/',
    SCHOOL_ROLE_MODULE: '/api/v1/menus/school-role-module/',
    REORDER: '/api/v1/menus/reorder/',
  },
  MASTERS: {
    COUNTRIES: '/api/v1/masters/countries/',
    STATES: '/api/v1/masters/states/',
    CITIES: '/api/v1/masters/cities/',
    BOARDS: '/api/v1/masters/boards/',
    CLASSES: '/api/v1/masters/classes/',
    SECTIONS: '/api/v1/masters/sections/',
    SUBJECTS: '/api/v1/masters/subjects/',
    STREAMS: '/api/v1/masters/streams/',
    SUBJECT_GROUPS: '/api/v1/masters/subject-groups/',
    DEPARTMENTS: '/api/v1/masters/departments/',
    DESIGNATIONS: '/api/v1/masters/designations/',
    CATEGORIES: '/api/v1/masters/categories/',
  },
  SCHOOL_MASTERS: {
    TYPES: '/api/v1/school-masters/types/',
    LIST: (type) => `/api/v1/school-masters/${type}/`,
    DETAIL: (type, id) => `/api/v1/school-masters/${type}/${id}/`,
    BULK_IMPORT: (type) => `/api/v1/school-masters/${type}/bulk-import/`,
    EXPORT: (type) => `/api/v1/school-masters/${type}/export/`,
  },
  AUDIT_LOGS: {
    LIST: '/api/v1/audit-logs/',
    DETAIL: (id) => `/api/v1/audit-logs/${id}/`,
    FILTER_OPTIONS: '/api/v1/audit-logs/filter-options/',
  },
  SETTINGS: {
    SECTION: (section) => `/api/v1/settings/${section}/`,
  },
  SCHOOL_SETTINGS: {
    SECTIONS: '/api/v1/school-settings/sections/',
    ALL: '/api/v1/school-settings/all/',
    EFFECTIVE_ALL: '/api/v1/school-settings/effective/',
    SECTION: (section) => `/api/v1/school-settings/${section}/`,
    EFFECTIVE_SECTION: (section) => `/api/v1/school-settings/${section}/effective/`,
    PREVIEW_NUMBER: '/api/v1/school-settings/preview-number/',
  },
  NOTIFICATIONS: {
    LIST: '/api/v1/notifications/',
    DETAIL: (id) => `/api/v1/notifications/${id}/`,
    MARK_READ: (id) => `/api/v1/notifications/${id}/mark-read/`,
    MARK_ALL_READ: '/api/v1/notifications/mark-all-read/',
    UNREAD_COUNT: '/api/v1/notifications/unread-count/',
  },
  NEXUS_MAIL: {
    SEND: '/api/v1/nexus-mail/send/',
  },
  STORAGE: {
    FOLDERS: '/api/v1/storage/folders/',
    UPLOAD: '/api/v1/storage/upload/',
    DELETE: '/api/v1/storage/delete/',
  },
  FORMS: {
    LIST: '/api/v1/forms/',
    DETAIL: (id) => `/api/v1/forms/${id}/`,
    PUBLISH: (id) => `/api/v1/forms/${id}/publish/`,
    UNPUBLISH: (id) => `/api/v1/forms/${id}/unpublish/`,
    DUPLICATE: (id) => `/api/v1/forms/${id}/duplicate/`,
    SUBMISSIONS: (id) => `/api/v1/forms/${id}/submissions/`,
    PUBLIC: (slug) => `/api/v1/public/forms/${slug}/`,
    PUBLIC_SUBMIT: (slug) => `/api/v1/public/forms/${slug}/submissions/`,
  },
}
